openapi: 3.1.0
info:
  title: Java API Requests and Responses Workshop - Core Criteria
  description: Core API for the Requests and Responses workshop with no errors in this file
  version: 0.0.4
  contact:
    name: Responses and Requests

servers:
  - url: http://localhost:4000
tags:
  - name: authors
paths:
  /authors:
    post:
      tags:
        - authors
      operationId: authorsPost
      summary: Route to use (with a payload) when creating a new author
      description: New author creation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthor'
      responses:
        '201':
          description: Author created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
    get:
      tags:
        - authors
      summary: Plain GET to access the whole list
      description: Get all of the listed authors
      operationId: getAuthors
      responses:
        '200':
          description: Get all authors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllAuthors'
  /authors/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: Id of the author
          required: true
          schema:
            type: integer
      tags:
        - authors
      summary: Get a specific author using their ID
      description: Get one author from the list
      operationId: getSpecificAuthor
      responses:
        '200':
          description: Get a single author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

    put:
      tags:
        - authors
      summary: Update an existing author
      description: use the ID of an author to update them using the payload
      operationId: updateAuthor
      parameters:
        - name: id
          in: path
          description: The ID of the author to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthor'
      responses:
        '201':
          description: Author successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
    delete:
      tags:
        - authors
      summary: Delete an author using the ID
      description: Delete an author using their ID
      operationId: deleteAuthor
      parameters:
        - name: id
          in: path
          description: The ID of the author to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted the Author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

components:
  schemas:
    CreateAuthor:
      type: object
      required: [name, email]
      properties:
        name:
          type: string
          example: "JRR Tolkien"
        email:
          type: string
          example: "jrr@tolkien.com"
    Author:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "JRR Tolkien"
        email:
          type: string
          example: "jrr@tolkien.com"
    AllAuthors:
      type: array
      items:
        $ref: '#/components/schemas/Author'
